apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
spec:
  type: NodePort
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30149
